Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.network "private_network", ip: "192.168.56.4"
    config.vm.provider "virtualbox" do |v|
      v.cpus = 4
      v.memory = 10000
    end
  end